const endpoints = {
  // 'baseUri': 'https://bini-qcommerce-backend.herokuapp.com',
  // 'baseUri': 'http://localhost:3000',
  'baseUri': 'http://localhost:8080',
  'signIn': '/auth/login',
  'signUp': '/auth/register',
  'items': '/items',
  'stores': '/stores',
  'users': '/users',
  'observations': '/observations',
  'viewAllObservations': '/observations/view/all',
  'verify_multiple_observation': '/observations/multiple/verify',
  'unverify_multiple_observations': '/observations/multiple/unverify',
  'verifyObservation': (id) => (`${endpoints.observations}/verify/${id}`),
  'unverifyObservation': (id) => (`${endpoints.observations}/unverify/${id}`),
  'updateObservation': (id) => (`${endpoints.observations}/${id}`),
  'extraObservation': '/observations/extra',
  'verifiedObservations': '/observations/verified',
  'visits': '/visits',
  'actions': '/actions',
  'addRemoveItem': '/basket-items/add-remove',
  'backendVersion': '/app-version',
  'getVisitImages': '/visits/images',
  'getShelf': '/camera/get-shelf',
  'getCameras': '/camera/get-cameras',
  'getAllCategories': '/categories/all',
  'getStoreProducts': '/store-products',
  'createStoreProduct': '/store-products',
  'updateStoreProduct': '/store-products',
  'organizationStoreAccess': '/organization/store/access',
  'organizationUserAccess': '/organization/user/access',
  'organizations': '/organizations',
};
export default endpoints;
