export const AUTH = 'AUTH';
export const GET_USER_BY_ID = 'GET_USER_BY_ID';
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const USER_ERROR = 'USER_ERROR';
export const LOGOUT = 'LOGOUT';
export const AUTO_LOGIN = 'AUTO_LOGIN';

export const GET_STORES = 'GET_STORES';
export const GET_STORE_ITEMS = 'GET_STORE_ITEMS';
export const GET_OBSERVATION_VISITS = 'GET_OBSERVATION_VISITS';
export const CHANGE_SELECTED_STORE = 'CHANGE_SELECTED_STORE';

export const GET_OBSERVATIONS = 'GET_OBSERVATIONS';
export const INIT_FETCHING_VERIFIED_OBSERVATIONS = 'INIT_FETCHING_VERIFIED_OBSERVATIONS';
export const GET_VERIFIED_OBSERVATIONS = 'GET_VERIFIED_OBSERVATIONS';

export const PREVIOUS_OBSERVATION = 'PREVIOUS_OBSERVATION';
export const INIT_MULTI_VERIY_ACTION = 'INIT_MULTI_VERIY_ACTION';
export const INIT_MULTI_UNVERIY_ACTION = 'INIT_MULTI_UNVERIY_ACTION';
export const CHANGE_SELECTED_OBSERVATION = 'CHANGE_SELECTED_OBSERVATION';
export const GET_OBSERVATION_ACTIONS = 'GET_OBSERVATION_ACTIONS';
export const UPDATE_OBSERVATION = 'UPDATE_OBSERVATION';
export const UPDATE_MULTIPLE_COMMON_DATA_OBSERVATION = 'UPDATE_MULTIPLE_COMMON_DATA_OBSERVATION';
export const SET_SELECTED_OBSERVATION = 'SET_SELECTED_OBSERVATION';
export const MULTIPLE_VERIFY_OBSERVATIONS = 'MULTIPLE_VERIFY_OBSERVATIONS';
export const MULTIPLE_UNVERIFY_OBSERVATIONS = 'MULTIPLE_UNVERIFY_OBSERVATIONS';
export const NEXT_OBSERVATION = 'NEXT_OBSERVATION';
export const CREATE_ACTION = 'CREATE_ACTION';

export const AUTH_ERROR = 'AUTH_ERROR';
export const OBSERVATION_ERROR = 'OBSERVATION_ERROR';
export const ACTION_ERROR = 'ACTION_ERROR';
export const STORE_ERROR = 'STORE_ERROR';
export const VISIT_ERROR = 'VISIT_ERROR';
export const SET_NEW_COMMAND_SUGGESTIONS = 'SET_NEW_COMMAND_SUGGESTIONS';
export const GET_OBSERVATIONS_AFTER_LOAD = 'GET_OBSERVATIONS_AFTER_LOAD';
export const TURN_ON_TYPING_MODE = 'TURN_ON_TYPING_MODE';
export const TURN_OFF_TYPING_MODE = 'TURN_OFF_TYPING_MODE';
export const TOGGLE_VIDEO_PLAYER = 'TOGGLE_VIDEO_PLAYER';
export const LOAD_SELECTED_STORE_ID = 'LOAD_SELECTED_STORE_ID';

export const INIT_FETCHING_ACTIONS = 'INIT_FETCHING_ACTIONS';
export const INIT_FETCHING_OBSERVATIONS = 'INIT_FETCHING_OBSERVATIONS';
export const INIT_FETCHING_VISITS = 'INIT_FETCHING_VISITS';
export const ADD_OBSERVATION = 'ADD_OBSERVATION';
export const GET_VISIT_IMAGES = 'GET_VISIT_IMAGES';
export const GET_ORGANIZATIONS = 'GET_ORGANIZATIONS';
